# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9652c4fc6fd99ccc4c9cacc2164cee80130d884334cdec44292285d135666f4197246fa7cb651cf342adb296bf2aa59aa7f6e13715b5da0316a5fa1d5b6fefa4

test:
  secret_key_base: 755d4bd57ac6ccf4030edc966c34bbad274ec8a2fd760c688a2fcc64aa6a0667a8f6e9caa92ca3000ac758e91cfa0e076b09f5f0ee582e5d5be15e4b05e1bae9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
